### ISSUE TITLE
css is broken in Map.Apps 4.6

### ISSUE THREAD

**Issue by matthiasdaues** [conterra/mapapps-charting#6]
Die Titel der Reiter des Charting-Widget werden nicht mehr über dem Charting-Canvas angezeigt, sondern daneben.

![image](https://user-images.githubusercontent.com/601326/56974273-cf4cc400-6b6e-11e9-8c8c-eefaf46b819b.png)

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-charting/releases/tag/1.5.1

**Comment by matthiasdaues** [comment]
ha. super :)
besten Dank dafür.
