### ISSUE TITLE
Sample funktioniert nicht mehr

### ISSUE THREAD

**Issue by schenardi** [conterra/mapapps-charting#9]
sample app funktioniert nicht mehr.

Ursache dürfte beim querybuilder liegen, seit glaube ich version 4.11 wird in der Konstellation mit "editable": false  in den Options ein sort (array) benötigt.

                    "options": {
                        "editable": false,
                        "mode": "builder",
                        "count": -1,
                        "ignoreCase": false,
                        "locale": {
                            "language": "en",
                            "country": "EN"
                        },
                        "sort": [
                            {
                                "attribute": "details",
                                "descending": true
                            }
                        ]
                    }

**Comment by sholtkamp** [comment]
Fixed by #11
